# Generated by Django 5.2.4 on 2025-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expressao', models.CharField(max_length=50, verbose_name='Expressão')),
                ('resultado', models.CharField(max_length=50, verbose_name='Resultado')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
        ),
    ]
